print("Welcome to the calculator program!")
print("Which mathematical operation would you like to perform?")
print("Your choices are: addition, subtraction, multiplication, division, power, remainder, quotient.")
choice = input()

if choice == "addition":
    print("You want to add two numbers!")
    print("Please input the first number: ")
    firstNumber = input()
    print("Please input the second number: ")
    secondNumber = input()
    print("Good job!")
    answer = float(firstNumber) + float(secondNumber)
    print(firstNumber + " plus " + secondNumber + " is: " + str(answer))
elif choice == "subtraction":
    print("You want to subtract two numbers!")
    print("Please input the first number: ")
    firstNumber = input()
    print("Please input the second number: ")
    secondNumber = input()
    print("Good job!")
    answer = float(firstNumber) - float(secondNumber)
    print(firstNumber + " minus " + secondNumber + " is: " + str(answer))
elif choice == "multiplication":
    print("You want to multiply two numbers!")
    print("Please input the firstNumber: ")
    firstNumber = input()
    print("Please input the secondNumber: ")
    secondNumber = input()
    print("Good job!")
    answer = float(firstNumber) * float(secondNumber)
    print(firstNumber + " multiply by " + secondNumber + " is: " + str(answer))
elif choice == "division":
    print("You want to divide two number!")
    print("Please input the firstNumber: ")
    firstNumber = input()
    print("Please input the secondNumber: ")
    secondNumber = input()
    print("Good job!")
    answer = float(firstNumber) / float(secondNumber)
    print(firstNumber + " divided by " + secondNumber + " is: " + str(answer))
elif choice == "power":
    print("You want to get power of some number!")
    print("Please input the base: ")
    base = input()
    print("Please input the exponent: ")
    exponent = input()
    print("Good job!")
    answer = float(base) ** float(exponent)
    print(base + " to the power of " + exponent + " is: " + str(answer))
elif choice == "remainder":
    print("You want to divide two numbers and return the remainder!")
    print("Please input the numerator: ")
    numerator = input()
    print("Please input the denominator: ")
    denominator = input()
    print("Good job!")
    answer = float(numerator) % float(denominator)
    print(numerator + " divided by " + denominator + " has a remainder of: " + str(answer))
elif choice == "quotient":
    print("You want to divide two numbers and return the quotient!")
    print("Please input the numerator: ")
    numerator = input()
    print("Please input the denominator: ")
    denominator = input()
    print("Good job!")
    answer = float(numerator) // float(denominator)
    print(numerator + " divided by " + denominator + " has a quotient of: " + str(answer))
else:
    print("I'm sorry, I don't recognize that operation.")
    
print("Thank you for using the calculator program!")
print("End of Program")
